CC= gcc
LIB=
FLAG= -Wall -Wextra -pedantic -lm
RULES=
OBJ=

#build as a single program
diatonic: diatonicfreqgen.c notetable.h $(RULES)
	$(CC) $(LIB) $(FLAG) $(OBJ) diatonicfreqgen.c -o diatonic.o


#build the object files

