CC= gcc
LIB=
FLAG= -Wall -Wextra -pedantic -lm
RULES=
OBJ=

#build as a single program
12tone: 12tonefreqgen.c $(RULES)
	$(CC) $(LIB) $(FLAG) $(OBJ) 12tonefreqgen.c -o 12tone.o


#build the object files

